# Generated by Django 4.2.13 on 2024-06-14 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
